config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#home'
get 'about', to: 'welcome#about'

resources :articles
get 'signup', to: 'users#new'
resources :users , except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]

get 'my_friends', to: 'users#my_friends'
resources :users, only:[:show]
resources :friendships

get 'search_friends', to: 'users#search'
get 'add_friend', to: "users#add_friend"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase}
	validates :username, presence: true, uniqueness: { case_sensitive: false },length: { minimum: 3, maximum: 30 }
	validates :email, presence: true, length: { maximum: 100 }, uniqueness: true
	validates :email, email_format: { message: 'Invalid email format' }
	has_secure_password
	has_many :friendships
	has_many :friends, through: :friendships

	def not_friends_with?(friend_id)
		friendships.where(friend_id: friend_id).count < 1
	end

	def full_name
		return "#{first_name} #{last_name}".strip if (first_name || last_name)
		"//" 
	end

	def except_curent_user(users)
		users.reject { |user| user.id == self.id }
	end

	def self.search(param)
		return User.none if param.blank?

		param.strip!
		param.downcase!
		(first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
	end

	def self.first_name_matches(param)
		matches('first_name', param)
	end

	def self.last_name_matches(param)
		matches('last_name', param)
	end

	def self.email_matches(param)
		matches('email', param)
	end

	def self.matches(field_name, param)
		where("lower(#{field_name}) like ?", "%#{param}%")
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user,only: [:edit, :update,:show]
	before_action :require_same_user, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success]=  "Welceome #{@user.username}"
			redirect_to user_path(@user)
		else
			render'new'
		end	
	end

	def edit
		
	end

	def update
		if @user.update(user_params)
			flash[:success] = 'User Info updated'
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end

	def index
		@users = User.paginate(page: params[:page],per_page: 3)
	end

	def show
		
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = 'User And All Articles Created Was Successfully Deleted'
		redirect_to users_path
	end

	def my_friends
		@friendships = curent_user.friends
	end

	def search
		@users = User.search(params[:search_param])

		if @users
			@users = curent_user.except_curent_user(@users)
			render partial: 'friends/lookup'
		else
			render status: :not_found, nothing: true
		end
	end

	def add_friend
		@friend= User.find(params[:friend])
		curent_user.friendships.build(friend_id: @friend.id)

		if curent_user.save
			redirect_to my_friends_path
			flash[:notice] = 'You Now Friend'
		else
			redirect_to my_friends_path
			flash[:error] = 'Some Thing Wrong'
		end
	end

	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end

	def set_user
		@user = User.find(params[:id])
	end
	
	def require_same_user
		if curent_user != @user and !curent_user.admin?
			flash[:danger] = 'You Can Edit Your Own Account'
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? and !curent_user.admin?
			flash[:danger] = 'Only Admin Can Do That Action'
			redirect_to root_path
		end
	end
end

app/views/users/edit.html.erb
<h1> Edit Page</h1>

<%= render 'shared/errors', art: @user %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: 'form-horizontal', role: 'form' }) do |u| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :first_name %>
				</div>
				<div class="col-sm-8">
				<%= u.text_field :first_name, class: "form-control", placeholder: 'First_name', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :last_name %>
				</div>
				<div class="col-sm-8">
				<%= u.text_field :last_name, class: "form-control", placeholder: 'Last_name', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :Username %>
				</div>
				<div class="col-sm-8">
					<%= u.text_field :username, class: "form-control", placeholder: 'Username', autofoucus: true %>	
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :Email %>
				</div>
				<div class="col-sm-8">
				<%= u.email_field :email, class: "form-control", placeholder: 'Email', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :Password %>
				</div>
				<div class="col-sm-8">
				<%= u.password_field :password, class: "form-control", placeholder: 'password', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= u.submit class: 'btn btn-primary btn-lg'%>	
				</div>
			</div>
		<%end%>
		<div class="col-xs-4 col-xs-offset-5">
			<%= link_to 'showing all articles', articles_path %>
		</div>	
	</div>
</div>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>

<div align="center">
	<%= will_paginate %>		
</div>
<div align="center">
	<% @users.each do |u| %>
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="well well-lg">
					<div class="article-title">
			 			<%= link_to u.username, user_path(u) %>
			 			<h4 class="article-count">
			 				{ <%= pluralize(u.articles.count, "article") if u.articles %> }
			 			</h4>
					</div>
					<% if curent_user == u || curent_user.admin?  %>
						<div class="article-actions">
							<%=link_to "Edit User", edit_user_path(u), class: 'btn btn-xs btn-primary' %> |
							<%= link_to "Delete User", user_path(u), method: :delete,
				 				data: {confirm:'Are You Sure'},
				 				class: 'btn btn-xs btn-danger' %>	
						</div>
					<%end%>
				</div>
			</div>
		</div> 		
	<%end%>	
</div>
<div align="center">
	<%= will_paginate %>
</div>

app/views/users/my_friends.html.erb
<h4>Friends</h4>
<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th colspan='3' class="page-header">
					<h2>My Friends</h2>
				</th>
			</tr>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @friendships.each do |f| %>
			<tr>
				<td><%= f.username %></td>
				<td><%= f.email %></td>
				<td>
					<%= link_to 'View Profile', user_path(f), class:'btn btn-primary btn-xs' %>
					<%= link_to 'Remove Friend', friendship_path(f), method: :delete,
						 date: {confirm:'Are You Sure'}, class: 'btn btn-xs btn-danger' %>
				</td>
			</tr>
			<%end%>
		</tbody>
	</table>	
<%else%>
	<div class="row col-lg-12">
		<p class="lead"> You Dont Have Any Friend's</p>
	</div>
<%end%>

app/views/users/new.html.erb
<h1> Signup Page</h1>

<%= render 'shared/errors', art: @user %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: 'form-horizontal', role: 'form' }) do |u| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :first_name %>
				</div>
				<div class="col-sm-8">
				<%= u.text_field :first_name, class: "form-control", placeholder: 'First_name', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :last_name %>
				</div>
				<div class="col-sm-8">
				<%= u.text_field :last_name, class: "form-control", placeholder: 'Last_name', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :Username %>
				</div>
				<div class="col-sm-8">
					<%= u.text_field :username, class: "form-control", placeholder: 'Username', autofoucus: true %>	
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :Email %>
				</div>
				<div class="col-sm-8">
				<%= u.email_field :email, class: "form-control", placeholder: 'Email', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= u.label :Password %>
				</div>
				<div class="col-sm-8">
				<%= u.password_field :password, class: "form-control", placeholder: 'password', autofoucus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= u.submit class: 'btn btn-primary btn-lg'%>	
				</div>
			</div>
		<%end%>
		<div class="col-xs-4 col-xs-offset-5">
			<%= link_to 'showing all articles', articles_path %>
		</div>	
	</div>
</div>

app/views/users/show.html.erb
<h2 align="center"> Welcome to: <%= @user.username %> Page</h2>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user %>
	</div>
</div>
<h4 align="center"><%= @user.username%>'s articles</h4>

<h1 align="center">Listing Articles belongs to <%= @user.username %></h1>

<div align="center">
	<% @user.articles.each do |t| %>
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="well well-lg">
					<div class="article-title">
			 			<%= link_to t.title, article_path(t) %>
					</div>
					<div class="article-body">
						<%= truncate(t.description, lenght: 100) %>
						<div class="article-meta">
							<small> Created By: <%= t.user.username if t.user %>,
												<%= time_ago_in_words(t.created_at) %> ago,
									last Updated: <%= time_ago_in_words(t.updated_at) %> ago
							</small>
						</div>				
					</div>
					<div class="article-actions">
						<%=link_to "Edit", edit_article_path(t), class: 'btn btn-xs btn-primary' %> |
						<%= link_to "Delete", article_path(t), method: :delete,
			 				data: {confirm:'are u sure'},
			 				class: 'btn btn-xs btn-danger' %>	
					</div>
				</div>
			</div>
		</div> 		
	<%end%>	
</div>