config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#home'
get 'about', to: 'welcome#about'

resources :articles
get 'signup', to: 'users#new'
resources :users , except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]

get 'my_friends', to: 'users#my_friends'
resources :users, only:[:show]
resources :friendships

get 'search_friends', to: 'users#search'
get 'add_friend', to: "users#add_friend"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name, presence: true, length: { minimum: 3, maximum: 25}
	validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, only: [:create, :new, :update, :edit]

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = 'Category Created'
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def index
		@categories = Category.paginate(page: params[:page], per_page:5)
	end

	def new
		@category = Category.new	
	end

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.articles.paginate(page: params[:page],per_page: 5)
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success] = 'Category Updated!'
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? and !curent_user.admin?)
			flash[:danger] = 'Only Admin Can Create & Update Categories'
			redirect_to root_path
		end
	end
end

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category) %> &nbsp; </span>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>

<%= render 'shared/errors', art: @category %>

<%= form_for(@category, :html => {class: 'form-horizontal', role: 'form' }) do |c| %>
	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= c.label :Name %>
		</div>
		<div class="col-sm-8">
			<%= c.text_field :name, class: "form-control", placeholder: 'Category name', autofoucus: true %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= c.submit class: 'btn btn-primary btn-lg'%>	
		</div>
	</div>
<%end%>
<div class="col-xs-4 col-xs-offset-5">
	<%= link_to 'showing all articles', articles_path %>
</div>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<div align="center">
	<%= will_paginate %>
	<% @categories.each do |category| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<l class="article-title">
						<%= link_to "#{category.name}", category_path(category) %> 
					</l>
					<li><small><%= pluralize(category.articles.count, "Article") %></small></li>
					<% if logged_in? and curent_user.admin? %>
						<%= link_to 'Edit Category', edit_category_path(category) %>
					<%end%>
				</div>
			</div>
		</ul>
	<%end%>
	<%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new Category</h1>

<%= render 'shared/errors', art: @category %>

<%= form_for(@category, :html => {class: 'form-horizontal', role: 'form' }) do |c| %>
	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= c.label :Name %>
		</div>
		<div class="col-sm-8">
			<%= c.text_field :name, class: "form-control", placeholder: 'Category name', autofoucus: true %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= c.submit class: 'btn btn-primary btn-lg'%>	
		</div>
	</div>
<%end%>
<div class="col-xs-4 col-xs-offset-5">
	<%= link_to 'showing all articles', articles_path %>
</div>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1> 
<div align="center"><%= will_paginate @category_articles%></div>
<div align="center">
	<% @category_articles.each do |t| %>
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="well well-lg">
					<div class="article-title">
			 			<%= link_to t.title, article_path(t) %>
					</div>
					<div class="article-body">
						<%= truncate(t.description, lenght: 100) %>
						<div class="article-meta">
							<small> Created By: <%= t.user.username if t.user %>,
												<%= time_ago_in_words(t.created_at) %> ago,
									last Updated: <%= time_ago_in_words(t.updated_at) %> ago
							</small>
						</div>				
					</div>
					<% if t.categories.any? %>
						<p>Categories: <%= render t.categories%> </p>
					<%end%>
					<% if logged_in? && (curent_user == t.user || curent_user.admin?) %>
						<div class="article-actions">
							<%=link_to "Edit", edit_article_path(t), class: 'btn btn-xs btn-primary' %> |
							<%= link_to "Delete", article_path(t), method: :delete,
				 				data: {confirm:'are u sure'},
				 				class: 'btn btn-xs btn-danger' %>	
						</div>
					<% end %>
				</div>
			</div>
		</div> 		
	<%end%>	
</div>
<div align="center"><%= will_paginate @category_articles %></div>